home_assistant:
  api_endpoint: 'http://127.0.0.1:8123/api'
  access_token: ''
  # api_password: ''
  verify_cert: false
buttons:
  - mac: XX:XX:XX:XX:XX:XX
    event: toggle_light
  - mac: YY:YY:YY:YY:YY:YY
    event: turn_ac_on
